region      = "us-east-1"
app_name    = "ground-station"
base_domain = "oliver-bilbie.co.uk"
full_domain = "ground-station.oliver-bilbie.co.uk"
cert_arn    = "arn:aws:acm:us-east-1:012345678910:certificate/********-****-****-****-************"
